blueprint:
  name: Mute mediaplayer when calling.
  description: >
    Mute a mediaplayer when phone rings or is calling.
    Only when person is home and the mediaplayer is playing.
  domain: automation
  input:
    phone_state:
      name: Phone State sensor
      description: All sensors form the mobile app. Select the phone state sensor here.
      selector:
        target:
          entity:
            integration: mobile_app
            domain: sensor
    person:
      name: Person
      description: Select the person that needs to be home.
      selector:
        target:
          entity:
            domain: person
    media_player: 
      name: Media Player
      description: Select the media player that needs to be muted.
      selector:
        target:
          entity:
            domain: media_player

trigger:
  - platform: state
    entity_id: !input phone_state
    to: "ringing"
  - platform: state
    entity_id: !input phone_state
    to: "offhook"
condition:
  - condition: state
    entity_id: !input person
    state: home
  - condition: state
    entity_id: !input media_player
    state: playing
action:
  - service: media_player.volume_mute
    entity_id: !input media_player
    data:
      is_volume_muted: true
  - wait_for_trigger:
    - platform: state 
      entity_id: !input phone_state
      to: "idle" 
    timeout:
      seconds: 300
  - service: media_player.volume_mute
    entity_id: !input media_player
    data:
      is_volume_muted: false